import type { PageConfig } from "../types";

export const homePage = {
    id: "page-home",
    siteId: "demo-site",
    slug: "home",
    title: "Website Manager Demo",
    status: "draft",
    schemaVersion: 1,

    seo: {

        title: "Website Manager Demo",
        description: "A configuration-driven website renderer demo"

    },

    blocks: [

        {
            "id": "hero-1",
            "type": "hero",

            "props": {
                "title": "Website Manager V2 -- Build websites from configuration",
                "subtitle": "The page you are seeing is generated by the Website Manager Renderer."
            }
        },

        {
            "id": "feature-1",
            "type": "feature",

            "props": {
                "items": [
                    "Configuration-driven rendering",
                    "Runtime schema validation",
                    "Reusable React components"
                ]
            }
        },

        {
            "id": "footer-main",
            "type": "footer",

            "props": {
                "text": "© 2026 Website Manager Demo"
            }
        }

    ]

} satisfies PageConfig;